- name: install httplib2
  sudo: true
  pip: name=httplib2

- name: get SSH keys from GitHub
  uri: >
    url="https://github.com/{{ item }}.keys"
    return_content=true
  register: ssh_keys
  with_items: add_ssh_keys_from_github.usernames

- name: Adding SSH keys to authorized_keys
  authorized_key: user="{{ user }}" key="{{ item.content }}"
  with_items: ssh_keys.results
